apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-country-deployment
  labels:
    app: my-country-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-country-service
  template:
    metadata:
      labels:
        app: my-country-service
    spec:
      containers:
        - name: my-country-service
          image: yassineamri/country_service
          ports:
            - containerPort: 8082
          
